### ISSUE TITLE
Both the RelativeTimeFormatter and the unit test appear to be implemented incorrectly

### ISSUE THREAD

**Issue by dpocock** [opentelecoms-org/jsmpp#1]
According to the spec, SMPP v3.4 s7.1.1, relative times are a time difference, here is the example from the spec:

```
For example, the following time format ‘020610233429000R”:
- would be interpreted as a relative period of 2 years, 6 months, 10 days, 23 hours, 34
minutes and 29 seconds from the current SMSC time.
```

The values returned by the RelativeTimeFormatter and the values in the unit test appear to be absolute values.

**Comment by pmoerenhout** [comment]
Fixed the testcase when running in April. For the relative time for months, it can be 1 month, 30, 29 or 28 days, depending on the month. With Joda Time or Java 8, new Duration and Period functions can be implemented. For now, it works.
