### ISSUE TITLE
How to get USSD operations?

### ISSUE THREAD

**Issue by MensurOwary** [opentelecoms-org/jsmpp#100]
Hello, I want to create a workflow as follows:
```
Device       USSD App
   |  ==pssr==> |     Dialed *100#
   | <==ussr==  |     Press 1 for details, 2 to pay, ...
   |  ==ussr==> |     1
   |     ..     |
   | <==pssr==  |     Thank you, Goodbye!
         or
   | <==ussr==  |     Some menu text
   |  ==stop==> |     Pressed CANCEL or network error
```
So, basically, I receive messages redirected by SMSC using `onAcceptDeliverSm` method on MessageReceiverListener. I can acquire service type as well. Now, my question is that how can I detect if it is a PSSR, USSR, USSN operation? 

I know `deliverSm.getOptionalParameters(Tag.USSD_SERVICE_OP)` gives me the OptionalParameter, but I don't know how to find out the operation type.

I know it is not an issue, can be asked on StackOverflow, but I've seen some questions asking for help, so I thought asking it here would be more appropriate.

**Comment by pmoerenhout** [comment]
In the SMPP release 5 manual, at paragraph 4.8..4.64:

tag ussd_service_op 0x0501
length 1
value (1 integer)
0 = PSSD indication
1 = PSSR indication
2 = USSR request
3 = USSN request
4-15 = reserved
16 = PSSD response
17 = PSSR response
18 = USSR confirm
19 = USSN confirm
20 to 31 = reserved
32 to 255 = reserved for vendor specific USSD operations

**Comment by MensurOwary** [comment]
I know that table, but I want to know how to get those values using jSMPP. I know this `deliverSm.getOptionalParameters(Tag.USSD_SERVICE_OP)` gives me OptionalParameter, but how can I extract those values from it? Sorry, if I was unclear.

**Comment by MensurOwary** [comment]
Figured it out.
```java
byte[] serialized = optionalParameter.serialize();
int tag = new BigInteger(Arrays.copyOfRange(serialized, 0, 2)).intValue(); // tag value in this case  1281
int len = new BigInteger(Arrays.copyOfRange(serialized, 2, 4)).intValue(); // length
int val = new BigInteger(Arrays.copyOfRange(serialized, 4, 5)).intValue(); // value : [0-3] or [16-19]
```

**Comment by pmoerenhout** [comment]
You can use this code snippet:

final OptionalParameter.Ussd_service_op ussdServiceOpOptionalParameter = (OptionalParameter.Ussd_service_op)deliverSm.getOptionalParameter(Tag.USSD_SERVICE_OP);
// This returns the byte value of the optional parameter
ussdServiceOpOptionalParameter.getValue();

Eventually, you can explicitly check the returned OptionalParameter class with instanceof.

**Comment by septs** [comment]
@MensurOwary i went a copy transceiver ussd command, the sample code.

>    |  ==pssr==> |     Dialed *100#

I don't know `*100#` the command is fill to ? field.

If possible, I would like to know the complete workflow code
