### ISSUE TITLE
Get value for RECEIPTED_MESSAGE_ID

### ISSUE THREAD

**Issue by Tsvetoslav88** [opentelecoms-org/jsmpp#102]
Hello,

I'm working on SMPP communication where I need to get both OptionalParamters from the server - 
"message_state" and "receipted_message_id".
For the first one I have no problem to get it but for the "receipted_message_id" I get the address instead of value:
`System.out.println(deliverSm.getOptionalParameter(Tag.MESSAGE_STATE));						System.out.println(deliverSm.getOptionalParameter(Tag.RECEIPTED_MESSAGE_ID));`

> DELIVERED
> org.jsmpp.bean.OptionalParameter$Receipted_message_id@3d

Thank you in advance!

**Comment by Tsvetoslav88** [comment]
Closing the issue found my problem. It's not a bug

**Comment by jcdiazhint** [comment]
Hello, I have the same issue, could you help me?

**Comment by pmoerenhout** [comment]
You need to cast it:
((OptionalParameter.COctetString)deliverSm.getOptionalParameter(OptionalParameter.Tag.RECEIPTED_MESSAGE_ID)).getValueAsString());

I could override the toString for convenience.

**Comment by jcdiazhint** [comment]
Hello, 
Thanks for your help.

**Comment by pmoerenhout** [comment]
I think the cast to (OptionalParameter.Receipted_message_id) is even clearer.
