### ISSUE TITLE
Optional parameters

### ISSUE THREAD

**Issue by mykolap** [opentelecoms-org/jsmpp#11]
There is a problem with receiving Optional parameters not in the known list.
In this case I get WARN about "parameter XXXX is not recognize"
But I need these parameters.

In Ukraine billing ids transfers via custom tlv parameters, different for different mobile operators.
I have to read them from DeliverSm, set them (plus some extra) in SubmitSm
I already add few new optional parameters in my version of JSMPP, but i have to make changes to jsmpp for every new parameter. 
I think getting/setting optional parameters via Map<Short, Parameter> would be better way, and no need of changing library in case of new tlv header detected.

**Comment by pmoerenhout** [comment]
Since the 2.2.3 version, it's possible to read the OptionalParameter by tag as short. The unknown Optional Parameter is passed as OctetString class. You can convert the byte array to whatever needed. I will look into the Map later.
