### ISSUE TITLE
TLS 1.2 Support - New Feature Request

### ISSUE THREAD

**Issue by kamochu** [opentelecoms-org/jsmpp#113]
Hello Team,

Apologies in case this feature already exists in the library. 

I am looking at setting up an SMPP Server (Gateway) where clients connect to and support TLS 1.2 to secure data in transit.

**Comment by pmoerenhout** [comment]
Hi, there is a class SSLSocketConnectionFactory which you can use. I will add an example.

**Comment by pmoerenhout** [comment]
I add SSL connection factories and updated the examples to optionally use SSL.

**Comment by kamochu** [comment]
Thank you very... I will try it out.
