### ISSUE TITLE
data coding for flash sms

### ISSUE THREAD

**Issue by shyamnb** [opentelecoms-org/jsmpp#117]
Hello,
I want to send flash sms from jsmpp. please let me know what should be the DataCoding format.

I tried this, "new GeneralDataCoding(Alphabet.ALPHA_UCS2, MessageClass.CLASS0, false)", but it is going as normal sms and storing inside msg box of mobile. 
In some blogs i can see it should be 0x10. can u please help me how to set it.

Thanks,
Shyam N

**Comment by pmoerenhout** [comment]
I used for Flash messages the new SimpleDataCoding(ALPHA_DEFAULT, CLASS0) as the DataCoding or new SimpleDataCoding(ALPHA_DEFAULT, CLASS0).toByte() if you need the byte value. This is DCS value 0xF0.
See SMPP 3.4 / 5.0 specifications and https://en.wikipedia.org/wiki/Data_Coding_Scheme.
