### ISSUE TITLE
Is there any plan for a new release?

### ISSUE THREAD

**Issue by TomasMorecom** [opentelecoms-org/jsmpp#12]
Hi.

You made a commit:
https://github.com/opentelecoms-org/jsmpp/commit/7a6ea536c4532cff4279098775af8ea5f558aa9f

based on this pull request:
https://github.com/opentelecoms-org/jsmpp/pull/8

Is there any chance you are going to make a new version number with this included?

We have a production platform depending on this fix to work with one of our SMPP gateways and now I have to build this based on a locally compiled library with this commit.
I would rather be able to build it with a maven "official" release number.

Regards,
Tomas

**Comment by Zoden** [comment]
Hi, guys!

Really need release with fix #8 , too. Seems not really good to build local versions.

Regards, 
Den

**Comment by pmoerenhout** [comment]
I just released version 2.2.2. Will work on more issues...
