### ISSUE TITLE
16 bits sar_msg_ref_num for Multipart SMS

### ISSUE THREAD

**Issue by azeemdin** [opentelecoms-org/jsmpp#121]
Hi,
In given example of Multi part SMS **SubmitMultipartMultilangualExample** currently it is sending 8 bits **sar_msg_ref_num**. Is it possible to send 16 bits **sar_msg_ref_num**? If yes can someone please guide how to implement this change.

**Comment by pmoerenhout** [comment]
The UDHIE_IDENTIFIER_SAR is 0x08 instead of 0x00. For the 16-bit reference, the reference is 2 bytes. The length is therefore also 1 byte larger, 4 instead of 3. See also https://en.wikipedia.org/wiki/User_Data_Header or ETSI/3GPP specifications. Please let me know if this is sufficient.

**Comment by azeemdin** [comment]
> The UDHIE_IDENTIFIER_SAR is 0x08 instead of 0x00. For the 16-bit reference, the reference is 2 bytes instead of 1 byte. The length is therefore also 1 byte larger, 4 instead of 3. See also https://en.wikipedia.org/wiki/User_Data_Header or ETSI/3GPP specifications. Please let me know if this is sufficient.

Thanks a lot for support. I have updated the code as below and it worked as expected

    protected static synchronized short getReferenceNumber() {
        refNum++;
        if (refNum == 65536) {
            refNum = 1;
        }        
        return refNum;
    }	


	private byte[][] splitUnicodeMessage(byte[] aMessage, Integer maximumMultipartMessageSegmentSize) {

		final byte UDHIE_HEADER_LENGTH = 0x06;
		final byte UDHIE_IDENTIFIER_SAR = 0x08;
		final byte UDHIE_SAR_LENGTH = 0x04;

		// determine how many messages have to be sent
		int numberOfSegments = aMessage.length / maximumMultipartMessageSegmentSize;
		int messageLength = aMessage.length;
		if (numberOfSegments > 255) {
			numberOfSegments = 255;
			messageLength = numberOfSegments * maximumMultipartMessageSegmentSize;
		}
		if ((messageLength % maximumMultipartMessageSegmentSize) > 0) {
			numberOfSegments++;
		}

		// prepare array for all of the msg segments
		byte[][] segments = new byte[numberOfSegments][];

		int lengthOfData;

		// generate new reference number
		short referenceNumber = getReferenceNumber();

		// split the message adding required headers
		for (int i = 0; i < numberOfSegments; i++) {
			if (numberOfSegments - i == 1) {
				lengthOfData = messageLength - i * maximumMultipartMessageSegmentSize;
			} else {
				lengthOfData = maximumMultipartMessageSegmentSize;
			}

			// new array to store the header
			segments[i] = new byte[7 + lengthOfData];

			// UDH header
			// doesn't include itself, its header length
			segments[i][0] = UDHIE_HEADER_LENGTH;
			// SAR identifier
			segments[i][1] = UDHIE_IDENTIFIER_SAR;
			// SAR length
			segments[i][2] = UDHIE_SAR_LENGTH;
			// reference number (same for all messages)
			System.arraycopy(ByteBuffer.allocate(2).putShort(referenceNumber).array(), 0, segments[i], 3, 2);			
			// total number of segments
			segments[i][5] = (byte) numberOfSegments;
			// segment number
			segments[i][6] = (byte) (i + 1);

			// copy the data into the array
			System.arraycopy(aMessage, (i * maximumMultipartMessageSegmentSize), segments[i], 7, lengthOfData);
			
			LOGGER.info("Message{} length: {}", i, segments[i].length);
		}
		return segments;
	}
