### ISSUE TITLE
jsmpp doesn't implement alert_notification for TRX (Transceiver mode)

### ISSUE THREAD

**Issue by killdashnine** [opentelecoms-org/jsmpp#122]
According to SMPP 3.4, alert_notification is allowed for both RX and TRX:

![image](https://user-images.githubusercontent.com/674985/88381500-d6c94000-cda6-11ea-9008-39fd4b1cfcee.png)

However SMPPSessionBoundTRX does not implement processAlertNotification and thus uses the one from SMPPSessionBoundTX which does nothing with it.

I will create pull request to fix this

**Comment by pmoerenhout** [comment]
Thanks for the catch!. I merged the PR.
