### ISSUE TITLE
Feature request: add option to get the next sequence number from a session

### ISSUE THREAD

**Issue by killdashnine** [opentelecoms-org/jsmpp#124]
For example, when I send alert_notification I need to supply a sequence number:

![image](https://user-images.githubusercontent.com/674985/88393103-6aa60680-cdbd-11ea-8443-7bb700c169fa.png)

`/* (non-Javadoc)
     * @see org.jsmpp.session.ServerSession#alertNotification(int, org.jsmpp.bean.TypeOfNumber, org.jsmpp.bean.NumberingPlanIndicator, java.lang.String, org.jsmpp.bean.TypeOfNumber, org.jsmpp.bean.NumberingPlanIndicator, java.lang.String, org.jsmpp.bean.OptionalParameter[])
     */
    @Override
    public void alertNotification(int sequenceNumber,
            TypeOfNumber sourceAddrTon, NumberingPlanIndicator sourceAddrNpi,
            String sourceAddr, TypeOfNumber esmeAddrTon,
            NumberingPlanIndicator esmeAddrNpi, String esmeAddr,
            OptionalParameter... optionalParameters) throws PDUStringException,
            IOException `

As the spec defines this should be unique. However there is currently no access to the sequence number from the session.

I believe adding a getNextSequenceNumber to AbstractSession would solve this by calling sequence.nextValue(); (getCurrentSequenceNumber could be nice too to get some metrics per session, but I think other ways would be better)

Further I am aware this doesn't really make sense for alert_notification as there is no response, however I think to be up to spec it would be nice to use the internal session sequence also used for submit_sm, deliver_sm.

Other option would be to refactor the alert_notification completely and use the deliver_sm/forward_sm style functions to send the alert_notification.

I would be happy to make a PR for this if you agree on what is the right way.

**Comment by pmoerenhout** [comment]
I think the sequenceNumber should be hidden from the caller, as it is with the other operations. As there is no need to handle any response, a new method like executeSendCommandNoResponse() (maybe a better name?) in AbstractSMPPOperation which not initiates a pending response should be added. If you can make a PR for it, that would be great!

**Comment by killdashnine** [comment]
Yes agreed, will put it on my TODO ;-)

**Comment by killdashnine** [comment]
One note, the sequence number should be set though according to spec, will see how I can deal with that :-)

**Comment by killdashnine** [comment]
This has been solved by @pmoerenhout by dropping the requirement to send sequence number for alertNotification
