### ISSUE TITLE
Print PDU

### ISSUE THREAD

**Issue by rgmarcanos** [opentelecoms-org/jsmpp#126]
Hello and thank you for this wonderful library, i have an small issue.

Sometimes our providers ask for the PDU when submitting a ticket, they have often sent us what is appears is the PDU in hex, can this be done with this library? i cant find any methods for this.

Best Regards,

Reinaldo

**Comment by pmoerenhout** [comment]
Hi Reinaldo, thanks for the feedback. I think this a nice feature to add. I will implement it with the next release.

**Comment by pmoerenhout** [comment]
Implemented full logging of the SMPP PDU at debug log level.
