### ISSUE TITLE
How to keep the smpp receive listener runing to receive sms anytime

### ISSUE THREAD

**Issue by DushyanthaHerath** [opentelecoms-org/jsmpp#133]
Is there a method to keep bind to smsc and receive listener running?

**Comment by pmoerenhout** [comment]
Yes, normally a connection must be bound for longer time. In the StressClient example, you'll see that a connection thread will bind, and be active until you decide to close it, or the remote party drops the connection. You can also use connection pooling for connection management. In jSMPP you're flexible to implement you own connection management.

**Comment by DushyanthaHerath** [comment]
Awesome. Let me try this out. Thanks for the prompt response

**Comment by DushyanthaHerath** [comment]
@pmoerenhout This absolutely works fine. Thanks

**Comment by pmoerenhout** [comment]
Great! I will close this issue.
