### ISSUE TITLE
There is a problem with GeneralDataCoding. Language does not convert properly.

### ISSUE THREAD

**Issue by mjc180** [opentelecoms-org/jsmpp#137]
Sent sms. But the language breaks.
If you send it "?ud558?uc774?" Message is sent.
I want to send this in Korean and Japanese.
How can I convert and send normally?
Ask for help
here, code

====================== code ==============================
String messageId = session.submitShortMessage("CMT",
                    TypeOfNumber.INTERNATIONAL, NumberingPlanIndicator.UNKNOWN, "821032590221",
                    TypeOfNumber.INTERNATIONAL, NumberingPlanIndicator.UNKNOWN, "821032590221",
                    new ESMClass(), (byte)0, (byte)1,  TIME_FORMATTER.format(new Date()), null,
                    new RegisteredDelivery(SMSCDeliveryReceipt.DEFAULT), (byte)0, new GeneralDataCoding(Alphabet.ALPHA_DEFAULT, MessageClass.CLASS1, false), (byte)0,
                    "하이".getBytes());
                LOGGER.info("Message submitted, message_id is {}", messageId);

====================== console ==============================
log4j:WARN No such property [append] in org.apache.log4j.ConsoleAppender.
[- INFO] 2020-10-13 13:59:29,630 - Connecting
[-DEBUG] 2020-10-13 13:59:29,632 - Connect and bind to smpp.bulksmsonline.com port 8889
[- INFO] 2020-10-13 13:59:29,805 - Connected from port 60016 to smpp.bulksmsonline.com/108.60.201.78:8889
[- INFO] 2020-10-13 13:59:29,808 - Starting PDUReaderWorker
[-DEBUG] 2020-10-13 13:59:29,810 - Sending SMPP message 00 00 00 2a 00 00 00 02 00 00 00 00 00 00 00 01 43 6f 72 70 46 69 39 38 34 00 46 69 76 65 30 39 21 21 00 63 70 00 34 00 00 00 
[- INFO] 2020-10-13 13:59:29,971 - Reading PDU session f4a10fbf in state OPEN: null
[-DEBUG] 2020-10-13 13:59:29,971 - Close session f4a10fbf in state OPEN
[-DEBUG] 2020-10-13 13:59:29,971 - Close session context f4a10fbf in state OPEN
[-DEBUG] 2020-10-13 13:59:29,971 - Close session f4a10fbf in state CLOSED
[-DEBUG] 2020-10-13 13:59:29,971 - PDUReaderWorker-f4a10fbf stopped

**Comment by pmoerenhout** [comment]
When you want to send Korean and Japanese characters there are multiple ways. If you specify the DCS to be Alphabet.ALPHA_DEFAULT, it's up to the SMSC to interpret your bytes. Normally this is Latin or GSM-7 bit encoded.
You can use JIS(X0208-1990) or Extended Kanji JIS (X 0212-1990) or KSC5601 as Data Coding Scheme (DCS) and then translate your Java String into the correct bytes. Another possibility is UCS-2. Select UCS2 as DCS, and then format the message bytes to UCS-2, which you can nearly get with the Java UTF-16BE charset. There is an example in the repo SubmitMultipartMultilangualExample or ArabicTest.

**Comment by pmoerenhout** [comment]
I also add in the latest 2.3.11 an UCS-2 class where you can check if a character is a valid UCS-2 character. The SubmitMultipartMultilangualExample will show encoding of a Java Unicode string into a UCS-2 encoded message.
