### ISSUE TITLE
Import in Java

### ISSUE THREAD

**Issue by TheVedhaGuy** [opentelecoms-org/jsmpp#14]
This is more of an Issue that I am facing and this is probably not an issue on your side. I was wondering why the import would not work for this project. When i try to import in eclipse, it tells me no projects found in import so overall I cannot import any of the files needed to begin my implementation. Any idea on how I can get around this?

**Comment by TheVedhaGuy** [comment]
Nvm got it to work.

**Comment by pmoerenhout** [comment]
Good to hear. Opening the pom.xml file, having a working Maven environment, should do the trick!
