### ISSUE TITLE
SMPPSession sendBind causes null array length error

### ISSUE THREAD

**Issue by TheVedhaGuy** [opentelecoms-org/jsmpp#15]
On Line 297 in the sendBind method. OptionalParameters seems to causes the connectAndBind method to break (as it is not declared and sendBind is called internally to this method). I commented this out this line and it is working fine. It did not seem like it would effect the system in any way. Let me know if I am wrong though.

**Comment by BlackRider97** [comment]
Yes I am also facing the same issue.
Actually issue is with this code
```
    private OptionalParameter[] readOptionalParameters(
            SequentialBytesReader reader) {
        if (!reader.hasMoreBytes())
            return null;
        List<OptionalParameter> params = new ArrayList<OptionalParameter>();
        while (reader.hasMoreBytes()) {
            short tag = reader.readShort();
            short length = reader.readShort();
            byte[] content = reader.readBytes(length);
            params.add(OptionalParameters.deserialize(tag, content));
        }
        return params.toArray(new OptionalParameter[params.size()]);
    }
```

**Comment by BlackRider97** [comment]
Fixed in master but not in any release :(

**Comment by BlackRider97** [comment]
@kostousov-ds please release new version from latest master. This issue is fixed in `master` branch

**Comment by pmoerenhout** [comment]
I will made a release 2.3.5 today... Thanks!

**Comment by pmoerenhout** [comment]
The change in readOptionalParameters was already in 2.3.0. Which version are you using?
