### ISSUE TITLE
Default deserialization of optional parameter

### ISSUE THREAD

**Issue by igniting** [opentelecoms-org/jsmpp#16]
Currently if the tag of optional parameter is not recognized, jsmpp treats it as a `COctetString` (https://github.com/opentelecoms-org/jsmpp/blob/master/jsmpp/src/main/java/org/jsmpp/bean/OptionalParameters.java#L109). This leads to losing last one byte of the data (since `COctetString` should be terminated by NULL). 
We have a use case where the SMSC sends a value of type `short` in custom optional parameter. Since jsmpp treats it as a `COctetString`, we end up losing one byte information.
In my opinion, we should by default treat the returned value as `OctetString` or add a check if the last character is null and then only parse it as a `COctetString`.
I can submit a patch after knowing your opinions.

**Comment by mykolap** [comment]
I think the main problem in using this library in production without changes - that it is not flexible with tlv.
And I am talking not only about default type.
Most mobile operators use custom tlv, they are not supported at all,
Some of the operators use non standard type for standard tlv.
And library is not flexible in handling these situations.

**Comment by igniting** [comment]
Most of the providers which we have worked with follow SMPP 3.4 protocol and we didn't face any issues till now. This issue happens in the case of parsing the status received in delivery receipt only.

**Comment by mykolap** [comment]
SMPP 3.4 allow to use custom tlv. And operators use them. If you can just skip them - good for you, but in my case I can't afford to skip that information.
Operator send transaction id in custom tlv of incoming messages. And when I sent response to abonent - I need to set transaction id in tlv of response, otherwise operator will reject the answer.

**Comment by pmoerenhout** [comment]
I'll change it anyway to OctetString. In the past the COctetString was not storing the trailing NULL, now it is. I was thinking of adding a mechnism to register additional OptionalParameters, so depending on the vendor you can add the deserialization code for that type.

**Comment by pmoerenhout** [comment]
Custom OptionalParameter can be decoded now, with:
final OptionalParameter.OctetString octetString = (OptionalParameter.OctetString) deliverSm.getOptionalParameter((short) 8192);        
        LOG.info("deliver_sm custom: '{}'", octetString.getValueAsString());
I added the getOptionalParameter(short) method for easy access.

**Comment by nyIdeas** [comment]
Hi All, Can anybody help me with write a custom TLV while submit sm. I got the idea of OptionalParameter usage but Unable to implement for a submit.
Thanks in advance.

**Comment by pmoerenhout** [comment]
Hi nyIdeas,

The session.submitShortMessage() method takes optional OptionalParameters as last parameter.
Just create a OptionalParameter like (these are just examples):
OptionalParameter op1 = new OptionalParameter.User_message_reference((short)2222);
OptionalParameter op2 = new OptionalParameter.COctetString((short)1111,"This is a C-octetstring");
The tag value (short) is either a predefined or an SMSC defined one.
Then call submitShortMessage like
final String messageId = session
    .submitShortMessage(
        sm.getServiceType(), ......... ,replaceIfPresentFlag,
        dataCoding, (byte) 0,
        data, op);
Regards, Pim

**Comment by nyIdeas** [comment]
Thanks alot pmoerenhout. I implemented the same and able to submit.
