### ISSUE TITLE
jcharset is GPL license that is incompatible with the Apache 2.0 license

### ISSUE THREAD

**Issue by coolbeevip** [opentelecoms-org/jsmpp#167]
https://github.com/opentelecoms-org/jsmpp/blob/afbd9722b1d7fae534e52b141bf4f031063a3bca/jsmpp-examples/pom.xml#L20-L23

Do you have other substitutes or alternatives that are available?

**Comment by pmoerenhout** [comment]
Good catch. I will see if there is an Apache Licenced charset, or otherwise I will create one.

**Comment by pmoerenhout** [comment]
I found these charsets, which are MIT licensed: https://github.com/brake/telecom-charsets. I will rewrite to use these or incorporate these libraries into the project.

**Comment by pmoerenhout** [comment]
jCharset is not used anymore, and replaced by a library with a MIT license.

**Comment by coolbeevip** [comment]
> jCharset is not used anymore, and replaced by a library with a MIT license.

Thank you for your time and effort!
