### ISSUE TITLE
org.jsmpp.extra.NegativeResponseException: Negative response 00000094 found

### ISSUE THREAD

**Issue by ShamineDsouza** [opentelecoms-org/jsmpp#172]
I am unable to send message even after successful connection  with SMSC .

I m getting an error while sending message , getting negative response 'Negative response 00000094 found '

When the error occurs command ID is 148. 
The failure occurs after validateResponse() method in AbstractSession.java. 

![image](https://user-images.githubusercontent.com/25946929/172599374-2d74a60d-391f-4292-adb6-efc22f0d3449.png)

Log: 

 /usr/bin/env c:\\Users\\.vscode\\extensions\\vscjava.vscode-java-debug-0.35.0\\scripts\\launcher.bat 
"C:\\Program Files\\Java\\jdk-18.0.1.1\\bin\\java.exe" -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:***** -XX:+ShowCodeDetailsInExceptionMessages -Dfile.encoding=UTF-8 @C:\\Users\\AppData\\Local\\Temp\\cp_4 org.jsmpp.examples.SimpleSubmitExample 
[main] INFO org.jsmpp.examples.SimpleSubmitExample - Connecting
[main] DEBUG org.jsmpp.session.SMPPSession - Connect and bind to **.***.**.** port *****
[main] INFO org.jsmpp.session.SMPPSession - Connected from port 62586 to /**.***.**.**:****
[PDUReaderWorker-03ee3da4] INFO org.jsmpp.session.SMPPSession - Starting PDUReaderWorker
[main] DEBUG org.jsmpp.DefaultPDUSender - Sending PDU *********************************************************************
[PDUReaderWorker-03ee3da4] DEBUG org.jsmpp.session.SMPPSession - Received PDU in session 03ee3da4 in state OPEN: **********************************************************
[pool-1-thread-1] DEBUG org.jsmpp.session.PDUProcessTask - Received PDU **********************************************************
[pool-1-thread-1] DEBUG org.jsmpp.session.SMPPSession - Changing processor degree to 3
[main] DEBUG org.jsmpp.session.AbstractSession - bind response with sequence_number 1 received for session 03ee3da4
[main] INFO org.jsmpp.examples.SimpleSubmitExample - Connected with SMSC with system id NEC-SMSC
[EnquireLinkSender-03ee3da4] DEBUG org.jsmpp.session.AbstractSession - Starting EnquireLinkSender for session 03ee3da4
[main] DEBUG org.jsmpp.DefaultPDUSender - Sending PDU **************************************************************************************************************************************************
[PDUReaderWorker-03ee3da4] DEBUG org.jsmpp.session.SMPPSession - Received PDU in session 03ee3da4 in state BOUND_TX: **************************************
[pool-1-thread-2] DEBUG org.jsmpp.session.PDUProcessTask - Received PDU ***********************************
[main] DEBUG org.jsmpp.session.AbstractSession - submit_sm response with sequence_number 2 received for session 03ee3da4
[main] ERROR org.jsmpp.examples.SimpleSubmitExample - Receive negative response
##  org.jsmpp.extra.NegativeResponseException: Negative response 00000094 found 
        at org.jsmpp.session.AbstractSession.validateResponse(AbstractSession.java:289)
        at org.jsmpp.session.AbstractSession.executeSendCommand(AbstractSession.java:356)
        at org.jsmpp.session.SMPPSession.submitShortMessage(SMPPSession.java:378)
        at org.jsmpp.examples.SimpleSubmitExample.main(SimpleSubmitExample.java:57)
[main] DEBUG org.jsmpp.session.AbstractSession - Unbind and close session 03ee3da4
[main] DEBUG org.jsmpp.DefaultPDUSender - Sending PDU **************************************
[PDUReaderWorker-03ee3da4] DEBUG org.jsmpp.session.SMPPSession - Received PDU in session 03ee3da4 in state BOUND_TX: **************************************
[pool-1-thread-3] DEBUG org.jsmpp.session.PDUProcessTask - Received PDU **************************************
[main] DEBUG org.jsmpp.session.AbstractSession - unbind response with sequence_number 3 received for session 03ee3da4
[main] DEBUG org.jsmpp.session.AbstractSession - Close session 03ee3da4 in state BOUND_TX
[main] DEBUG org.jsmpp.session.AbstractSession - Stop enquireLinkSender for session 03ee3da4
[EnquireLinkSender-03ee3da4] DEBUG org.jsmpp.session.AbstractSession - EnquireLinkSender stopped for session 03ee3da4
[PDUReaderWorker-03ee3da4] INFO org.jsmpp.session.SMPPSession - Reading PDU session 03ee3da4 in state BOUND_TX: Socket closed       
[PDUReaderWorker-03ee3da4] DEBUG org.jsmpp.session.AbstractSession - Close session 03ee3da4 in state BOUND_TX
[main] DEBUG org.jsmpp.session.AbstractSession - Close session context 03ee3da4 in state BOUND_TX
[PDUReaderWorker-03ee3da4] DEBUG org.jsmpp.session.AbstractSession - Close session context 03ee3da4 in state BOUND_TX
[PDUReaderWorker-03ee3da4] DEBUG org.jsmpp.session.SMPPSession - PDUReaderWorker-03ee3da4 stopped

Decoded PDU

00000049 - 73 (Command length)
00000004 - submit_sm (Command Id)
00000000 - ESME_ROK (Command status)
00000002 - 2 (Sequence number)
00 - '' (Service type)
05 - Alphanumeric (TON)
01 - ISDN (NPI)
'*******' (Octet string)
01 - International (TON)
01 - ISDN (NPI)
*********************** (Octet string)
00 - 0 (ESM class)
00 - Default_store_and_forward_short_message (PID)
01 - Normal (Priority flag)
00 - '' (Scheduled delivery time)
00 - '' (Validity period)
00 - None (Registered delivery)
00 - DontReplace (Replace if present)
11 - 17 (Data coding)
00 - Unused (Default msg id)
02 - 2 (Sm length)
4869 - 'Hi' (Short message)
Thank you

**Comment by ShamineDsouza** [comment]
Decoded PDU 



00000049 - 73 (Command length)
00000004 - submit_sm (Command Id)
00000000 - ESME_ROK (Command status)
00000002 - 2 (Sequence number)
------------------------------

00 - '' (Service type)
05 - Alphanumeric (TON)
01 - ISDN (NPI)
'*******' (Octet string)
01 - International (TON)
01 - ISDN (NPI)
*********************** (Octet string)
00 - 0 (ESM class)
00 - Default_store_and_forward_short_message (PID)
01 - Normal (Priority flag)
00 - '' (Scheduled delivery time)
00 - '' (Validity period)
00 - None (Registered delivery)
00 - DontReplace (Replace if present)
11 - 17 (Data coding)
00 - Unused (Default msg id)
02 - 2 (Sm length)
4869 - 'Hi' (Short message)

**Comment by pmoerenhout** [comment]
Hi, the status 0x00000094 is reserved in the SMPP spec 3.4 or 5.0. Can you contact your SMSC operator and ask what this error means ?

**Comment by ShamineDsouza** [comment]
Sure.  Thanks for your reply . I was able to solve it however by removing the + before the phone number.
Although we will ask about the error as suggested by you.
