### ISSUE TITLE
org.jsmpp.bean.OptionalParameter.COctetString.getValueAsString() returns a String which misses the last character

### ISSUE THREAD

**Issue by PascalSchumacher** [opentelecoms-org/jsmpp#18]
This is a repeat of:

https://code.google.com/p/jsmpp/issues/detail?id=140

which was closed as fixed, but

```java
    @Test
    public void test() {
        assertEquals("urgent", new OptionalParameter.Additional_status_info_text("urgent".getBytes()).getValueAsString());
    }
```
still fails with:

>org.junit.ComparisonFailure: expected:\<urgen[t]\> but was:\<urgen[]\>

By the way: Thanks for providing jsmpp. :+1:

**Comment by pmoerenhout** [comment]
Hi Pascal, I will look into this.

Regards, Pim

**Comment by PascalSchumacher** [comment]
Thanks Pim,

forgot to mention that I'm using jsmpp 2.2.2.

**Comment by pmoerenhout** [comment]
The value of the COctetString is the string plus a null character. When you test it, you must specify it:
@Test
  public void testAdditionalStatusInfoText() {
    byte[] content = "urgent\0".getBytes();
    COctetString op = new OptionalParameter.Additional_status_info_text(content);
    assertEquals("urgent", op.getValueAsString());
  }

If you need to construct it from a plain Java String, I can add the constructor like:
public static class Additional_status_info_text extends OptionalParameter.COctetString {
		public Additional_status_info_text(byte[] value) {
			super(Tag.ADDITIONAL_STATUS_INFO_TEXT.code(), value);
		}
		public Additional_status_info_text(String value) {
			super(Tag.ADDITIONAL_STATUS_INFO_TEXT.code(), value);
		}
	}
Do you need such a contructor?

**Comment by PascalSchumacher** [comment]
Hi Pim,

thanks for the quick response and the detailed explanation. :smiley: 

I stumbled over this while trying to update camel-smpp from jsmpp 2.1.1 to 2.2.2. The tests, which mock part of jsmpp contained the commented out assertions with the link to https://code.google.com/p/jsmpp/issues/detail?id=140

While a constructor that takes a String value would be helpful for the camel-smpp test, they can of course do without it. My knowledge of jsmpp and its usage is minimal, so I do not know if such a constructor would also be helpful for others. I let you decide whether it is a worthy addition.

Thanks again!

**Comment by PascalSchumacher** [comment]
Just noticed that you already added the constructor with https://github.com/opentelecoms-org/jsmpp/commit/517ed857cf79b36d2f56eb04c62c170c56cfbf4c :smile:
