### ISSUE TITLE
Allow 16 characters for the System ID and 9 characters for the Password as per SMPP Specification v3.4

### ISSUE THREAD

**Issue by dkodira** [opentelecoms-org/jsmpp#27]
As per the SMPP Protocol Specification v3.4, 16 characters are allowed for the System ID and 9 characters are allowed for the password.

But in the current implementation, 
Only 15 characters are allowed for the System ID and 8 characters are allowed for the Password.

In the method StringValidator.java

    static boolean isCOctetStringValid(String value, int maxLength) {
        if (value == null)
            return true;
        if (value.length() >= maxLength)
            return false;
        return true;

    }

    static boolean isCOctetStringValid(byte[] value, int maxLength) {
        if (value == null)
            return true;
        if (value.length >= maxLength)
            return false;
        return true;

So the '=' sign in the if statement shall be removed, to make sure that it accepts the allowed limit.

Proposed Change 
if (value.length >maxLength)......

**Comment by pmoerenhout** [comment]
The system_id is defined as C Octet String with Var Max 16 in the SMPP 3.4 spec. In par 3.1.1 (page 37), the C Octet String is explained. With Var Max 16, there is room for max 15 ASCII characters plus the NULL terminating character. The length defined in StringParameter is including the NULL character.
The isCOctetStringValid method validates a Java string (without terminating null).

**Comment by dkodira** [comment]
Thanks for the detailed Explaination.
