### ISSUE TITLE
SMPP Data Coding Scheme: Unknown (0x11)

### ISSUE THREAD

**Issue by marcinkowalczyk** [opentelecoms-org/jsmpp#31]
Hi,

 Looks like, that when sending SMS SMPP Data Coding Scheme is set to Unknown (0x11)

session.submitShortMessage is called with new GeneralDataCoding(ALPHA_DEFAULT, CLASS1, false)

GSM SMS Data Coding is set ok

From wireshark trace:

Data coding: 0x11
SMPP Data Coding Scheme: Unknown (0x11)
GSM SMS Data Coding
0001 .... = DCS Coding Group for SMS: SMS DCS: General Data Coding indication - Uncompressed text (0x01)
..0. .... = DCS Text compression: Uncompressed text
...1 .... = DCS Class present: Message class is present
.... 00.. = DCS Character set: GSM 7-bit default alphabet (0x00)
.... ..01 = DCS Message class: Class 1 - ME specific (0x01)
GSM CBS Data Coding
0001 .... = DCS Coding Group for CBS: CBS DCS: Language indication at beginning of message (0x01)
..01 0001 = DCS CBS Message language: UCS-2 (16-bit) - message preceded by language indication (0x11)

**Comment by marcinkowalczyk** [comment]
Hi,
 looks like, that if instead calling new GeneralDataCoding(ALPHA_DEFAULT, CLASS1, false) I use DATACODINGS.ZERO SMPP Data Coding Scheme is set to proper value, but Message Class is not set and following are set
0000 .... = DCS Coding Group for CBS: CBS DCS: Language using the GSM 7-bit default alphabet (0x00)
..00 0000 = DCS CBS Message language: German (0x00)

**Comment by pmoerenhout** [comment]
Hi, the DCS 0x11 is valid (See GSM 03.38 https://en.wikipedia.org/wiki/Data_Coding_Scheme). Seems that Wireshark doesn't decode properly. I will add some DCS tests to verify.

**Comment by pmoerenhout** [comment]
Added the org.jsmpp.bean.GeneralDataCodingTest test case.
