### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by oussoumab** [opentelecoms-org/jsmpp#40]
I'm trying to execute this example.
I get this erreur
I'm not familiar with SMPP
can any one help me
Regards.
[ERROR] Failed to execute goal on project jsmpp-examples: Could not resolve dependencies for project org.jsmpp:jsmpp-examples:jar:2.2.0-SNAPSHOT: Could not find artifact org.jsmpp:jsmpp:jar:2.2.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by pmoerenhout** [comment]
Hi oussoumab,
If you pull the latest build from Github, it will be version 2.2.4-SNAPSHOT. I can build it with the latest Maven 3.3.9 and Java 7/8. How do you run it ?

**Comment by urbaez22** [comment]
I'm facing exactly the same issue today.. But with version 2.3.10-SNAPSHOT..

`[ERROR] Failed to execute goal on project jsmpp-examples: Could not resolve dependencies for project org.jsmpp:jsmpp-examples:jar:2.3.10-SNAPSHOT: Failure to find org.jsmpp:jsmpp:jar:2.3.10-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]`

I'm compiling with Java 1.8.0_171..
