### ISSUE TITLE
SSL SMPP

### ISSUE THREAD

**Issue by mityushaa** [opentelecoms-org/jsmpp#42]
Does this lib support ssl? If so, how to use it.

**Comment by pmoerenhout** [comment]
The jSMPP supports SSL, by creating a SSL capable ConnectionFactory. This SSL ConnectionFactory must be instanced when the SMPPSession is constructed.
An example you can find in the Camel SMPP library (https://github.com/apache/camel/blob/master/components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppConnectionFactory.java).
I'm planning to add a example in the next version.

**Comment by pmoerenhout** [comment]
I've added org/jsmpp/session/connection/socket/SSLSocketConnectionFactory.java.
You can use this when connection like:
new SMPPSession(
            new SynchronizedPDUSender(new DefaultPDUSender(new DefaultComposer())),
            new DefaultPDUReader(),
            (ssl ? SSLSocketConnectionFactory.getInstance() : SocketConnectionFactory.getInstance()));
I will include in the release 2.2.5

**Comment by mityushaa** [comment]
thanks a lot!
