### ISSUE TITLE
Please release 2.2.4 with osgi fix

### ISSUE THREAD

**Issue by PascalSchumacher** [opentelecoms-org/jsmpp#43]
Hi,

it would be nice if you could release 2.2.4 with the fix: https://github.com/opentelecoms-org/jsmpp/commit/bc6207c736a474e5f0134942a3152d39faa4b962 which makes jsmpp work with osgi.

This would allow Apache Camel to directly use the jsmpp osgi bundle instead of repackaging it.

Thanks,
Pascal

**Comment by pmoerenhout** [comment]
I released version 2.2.4.

**Comment by PascalSchumacher** [comment]
Thank you very much!
