### ISSUE TITLE
Services Type Null

### ISSUE THREAD

**Issue by mdonalisio** [opentelecoms-org/jsmpp#51]
Service Type in submitSm parameter is null when i receive SMS

**Comment by pmoerenhout** [comment]
Could you explain a little bit more about the scenario? Do you have the raw binary data so I can reproduce?

**Comment by mdonalisio** [comment]
Yes sorry... I using this example "SMPPServerSimulator.java" in onAcceptSubmitSm method i print submitSm.getServiceType() and this is null, 

0000004e00000004000000000000000a00000039353735393031363900010139353735393031363900000000003030303030323030303030303030305200010000000b5072756562612054657374

This is a data to sending from client smpp... if you can tell me how to read this, i appreciate it.

Thanks.

**Comment by pmoerenhout** [comment]
The SMSC 3.4 specification says in 5.2.11, that a NULL value should be interpreted as default service type. In the submit_sm PDU definition, it says "Set to NULL for default SMSC settings". In your PDU, byte 17 is 00, so the service type is an empty COctetString, so null. I attached a test class.

**Comment by pmoerenhout** [comment]
Test an PDU to decompose as SubmitSM PDU:
[DecomposePDUTest.txt](https://github.com/opentelecoms-org/jsmpp/files/412711/DecomposePDUTest.txt)

**Comment by mdonalisio** [comment]
Thanks. :)
