### ISSUE TITLE
Java - Connect to SMPP server over SSL using JSMPP api

### ISSUE THREAD

**Issue by jeevanlalks** [opentelecoms-org/jsmpp#52]
Is there any way to connect to SMPP server over ssl from java application using JSMPP API?

Basically, my two questions are:

How do I specify as an SSL connection when open JSMPP session.
Where do I put the public certificate.

**Comment by pmoerenhout** [comment]
Yes, it's possible. You have to use the org.jsmpp.session.connection.socket.SSLSocketConnectionFactory (or create your own) in the latest jSMPP release. The SMPPOutboundSession has constructors which take the ConnectionFactory as parameter. If you need special checking of the public certificate, you need to use your own customized SSLSocketConnectionFactory...

**Comment by jeevanlalks** [comment]
Thanks, I will try your solution

**Comment by pmoerenhout** [comment]
Did you succeed ?

**Comment by igor-telxira** [comment]
Can someone provide an example code for successful connection to smpp secure 3550 port ?

**Comment by pmoerenhout** [comment]
There is the class SSLSocketConnectionFactory, which creates the SSL Socket. The SMPP Session can take the ConnectionFactory as parameter. I can add an example if needed...

**Comment by igor-telxira** [comment]
thank you. let me play with it for better understanding

**Comment by pmoerenhout** [comment]
I've finally added some SSL examples for the server and client.
