### ISSUE TITLE
Full fledged implementation of SMPPServerSimulator

### ISSUE THREAD

**Issue by madnaelo** [opentelecoms-org/jsmpp#59]
The current implementation of `SMPPServerSimulator` does not simulate all the scenarios. For-example, it does not uses any of the following constants
```
    public static final int STAT_ESME_RBINDFAIL = 0x0000000D;
    public static final int STAT_ESME_RINVPASWD = 0x0000000E;
    public static final int STAT_ESME_RINVSYSID = 0x0000000F;
    public static final int STAT_ESME_RCANCELFAIL = 0x00000011;
    public static final int STAT_ESME_RREPLACEFAIL = 0x00000013;
```

Therefore `SMPPServerSimulator` does not show full usage of it. It should simulate all the scenarios.

**Comment by pmoerenhout** [comment]
I implemented scenarios in the SMPP server simulator. You can specify a valid system id and password to be accepted by the server simulator.
