### ISSUE TITLE
How detect a long SMS MO ?

### ISSUE THREAD

**Issue by olivierbeyler** [opentelecoms-org/jsmpp#61]
Hello,
I use a MessageReceiverListener to receive SMS DR and SMS MO
I detect that is a SMS MO if deliverSM doesn't contain SMSC_DEL_RECEIPT
but I don't know how to detect that the SMS MO is a part (and witch part ) of a long SMS MO
Does someone has an idea to find this kind of information ?
Best regards

**Comment by pmoerenhout** [comment]
Normally is a SMS is part of an longer, concatenated message, it will contain a User Data Header. The ESM Class will have the UDH indicator set, and the User Data Header will contain the information for the total number, reference id, and part number. There are 8 and 16 bit reference numbers. It could be that the SMSC extracts this information and puts in the appropiate optional headers. Do you have an example ?

**Comment by olivierbeyler** [comment]
No I'm looking for one example :-)
