### ISSUE TITLE
ResponseTimeoutException after submit_sm on moderate to heavy load 

### ISSUE THREAD

**Issue by dacristo** [opentelecoms-org/jsmpp#63]
Hello, we are experiencing some strange behavior from the jsmpp implementation on moderate to heavy loads. The system fires ResponseTimeoutException even though in Wireshark I can see the submit_sm response for the sent message. This exception causes us to resend the message and at the  end the customer receives duplicate messages. Are there any other means of requesting a new submit_sm response from the SMSC

**Comment by pmoerenhout** [comment]
Do you have some details about how the PduProcessorDegree is set on the client and how many messages/second are send and what the window size (the max. messages outstanding) is when this is happening? Increasing the pduProcessorDegree will use more threads to handle the messages.

**Comment by dacristo** [comment]
Thank you for the response Pim, we did something similar, we increased the PduProcessorDegree and also prioritized the submit_sm_resp so it will be handled first. So far so good we do not see the problem anymore.
Best Regards and thank you for the answer.
