### ISSUE TITLE
Logging of optionalparameter causes NullPointerException for some SMSCs.

### ISSUE THREAD

**Issue by TomasMorecom** [opentelecoms-org/jsmpp#7]
In SMPPSession.java line 296 in method sendBind(..) the Sc_interface_version is retrieved from the OptionalParameters from the bindResponse (from the SMSC) for logging purposes only:

	    BindResp resp = (BindResp)executeSendCommand(task, timeout);
	    OptionalParameter.Sc_interface_version sc_version = resp.getOptionalParameter(Sc_interface_version.class);
	    if(sc_version != null) {
		    logger.info("Other side reports smpp interface version {}", sc_version);
	    }

When running towards proper SMSC'es this works ok, as I have already integrated with two real SMSCs. When running towards an SMPP SIM (in my case Selenium SMPPSim I am unable to configure the optionalparameters list in the bind response from the simulator. 
The consequence is that the optionalParameters in the BindResp is null.
The SMPP API doesnt handle this and causes a NullPointerException:

Exception in thread "main" java.lang.NullPointerException
	at org.jsmpp.bean.OptionalParameters.get(OptionalParameters.java:238)
	at org.jsmpp.bean.BindResp.getOptionalParameter(BindResp.java:61)
	at org.jsmpp.session.SMPPSession.sendBind(SMPPSession.java:297)
	at org.jsmpp.session.SMPPSession.connectAndBind(SMPPSession.java:234)
	at org.jsmpp.session.SMPPSession.connectAndBind(SMPPSession.java:201)

I think there should be a check to verify that optionalparameters is not null before trying to access it.

**Comment by TomasMorecom** [comment]
I have looked into this and the code in OptionalParameters.java line 235 is like this:

    @SuppressWarnings("unchecked")
    public static <U extends OptionalParameter> U get(Class<U> tagClass, OptionalParameter[] parameters)
    {
        for(OptionalParameter i: parameters) {
            if(i.getClass() == tagClass) {
                return (U)i;
            }
        }
        logger.info("optional tag " + tagClass + " not found");
        return null;
    }
This should work as the for loop should be skipped, but when debugging with the jsmpp api the code looks like this runtime (intellij decompiled class:)

    public static <U extends OptionalParameter> U get(Class<U> tagClass, OptionalParameter[] parameters) {
        OptionalParameter[] arr$ = parameters;
        int len$ = parameters.length;

        for(int i$ = 0; i$ < len$; ++i$) {
            OptionalParameter i = arr$[i$];
            if(i.getClass() == tagClass) {
                return i;
            }
        }

        logger.info("optional tag " + tagClass + " not found");
        return null;
    }

When len is retrieved the exception is thrown.

I am adding a pull request for this one.

**Comment by TomasMorecom** [comment]
It is also possible to fix this by omitting the whole part of reading the optionalParameters and logging the version.

**Comment by pmoerenhout** [comment]
I fixed the problem by checking the parameters for a null value. Other responses uses this as well.

**Comment by TomasMorecom** [comment]
Great. Can you post your changes when you have time?

**Comment by pmoerenhout** [comment]
Hi Tomas,

The changes you will find in this commit: https://github.com/opentelecoms-org/jsmpp/commit/7a6ea536c4532cff4279098775af8ea5f558aa9f

Pim

**Comment by pmoerenhout** [comment]
Fixed in release 2.2.2.
