### ISSUE TITLE
Add description from SMPP specification to NegativeResponseException error message?

### ISSUE THREAD

**Issue by PascalSchumacher** [opentelecoms-org/jsmpp#76]
Currently error messages of `NegativeResponseException` return for example `Negative response 0000000b found`.

In my opinion it would be helpful if the error messages included the description from the SMPP specification, e.g. `Negative response 0000000b (Invalid Destination Address) found.`

What do you think?

**Comment by pmoerenhout** [comment]
Yes, I think this is useful. Thanks!
