### ISSUE TITLE
Aboult jsmpp version

### ISSUE THREAD

**Issue by wsrfzd** [opentelecoms-org/jsmpp#79]
![qq 20180206160716](https://user-images.githubusercontent.com/12988777/35848152-febb3f46-0b57-11e8-81a2-3753050079cc.png)
![qq 20180206160756](https://user-images.githubusercontent.com/12988777/35848153-feeca8b0-0b57-11e8-93e9-24d7d1a5af2d.png)

Hi, The latest version I see from the maven repository is 2.3.5,but the latest version of this project is not. What's the reason?

**Comment by pmoerenhout** [comment]
Hi, when I look on Maven Central, I can see the version 2.3.6:
https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.jsmpp%22
but I think i forgot to tag it. I just did that. When it's indexed again, it will show up.

**Comment by pmoerenhout** [comment]
https://mvnrepository.com/artifact/org.jsmpp/jsmpp shows the tag now.
