### ISSUE TITLE
GSM 03.48 

### ISSUE THREAD

**Issue by b22sk2** [opentelecoms-org/jsmpp#81]
Is it possible to send GSM 03.48 message using jsmpp

**Comment by pmoerenhout** [comment]
Yes, I also maintain the GSM 03.48 library (https://github.com/opentelecoms-org/gsm0348). The binary messages generated with this library needs to be send with DCS F6 and PID 7F to reach the SIM via an envelope.

**Comment by Chuchu003** [comment]
I'm looking at how I can send OTA-update on a SIM as SMS and the automatically updates are installed

**Comment by pmoerenhout** [comment]
First you need to construct the binary message. For GSM 03.48 encrypted messages to update the SIM filesystem, or to send messages to open channels for HTTPS, you can use the library at https://github.com/opentelecoms-org/gsm0348, which by coincidence I also maintain. For SIM related SMS, use DCS 0xF6 and PID 0x7F.

**Comment by Chuchu003** [comment]
Can I modify or attach an algorithm to monitor the operations of the SIM card? Thanks a lot for the feedback!
