### ISSUE TITLE
£ sign is not being displayed correctly on handset

### ISSUE THREAD

**Issue by kamochu** [opentelecoms-org/jsmpp#83]
Hello team... I have an issue with some characters being displayed wrongly on the handset.

Sent content: £$%^&*96733{}@#
Delivered content: B#$%^&*96733{}@#

It appears the character £ is being misrepresented.

Below is a sample code block:
```
String message = "£$%^&*96733{}@#";

String messageId = session.submitShortMessage(
        null,
        TypeOfNumber.ALPHANUMERIC,
        NumberingPlanIndicator.UNKNOWN,
        "Uwiano",
        TypeOfNumber.INTERNATIONAL,
        NumberingPlanIndicator.ISDN,
        "254723624727",
        new ESMClass(),
        (byte) 0,
        (byte) 0,
        null,
        null,
        new RegisteredDelivery(SMSCDeliveryReceipt.DEFAULT),
        (byte) 0,
        new GeneralDataCoding(Alphabet.ALPHA_DEFAULT, MessageClass.CLASS1, false),
        (byte) 0,
        message.getBytes()
);
```

**Comment by pmoerenhout** [comment]
Hi Samuel, you are using DCS 00, which is the SMSC default alfabet. So the translation between SMPP and the GSM core mapping is done in the SMSC. It’s different between SMSC vendors. Who is the SMSC vendor and do you have their documentation?

**Comment by kamochu** [comment]
Hi @pmoerenhout . Thank you for your quick response. I am connecting to ZTE SMSC (Telco - Telkom Kenya). I do not have their documentation but I will request for it. I am experiencing the same issue with Airtel Malawi SMSC. 

Is there something the most common SMSC alphabet?

I have tried below but it did not help. I am in the right direction?

```
String message = "£$%^&*96733{}@#â, ê, î, ô, û, é ë, ï, ü [ this is it ]";

String messageId = session.submitShortMessage(
        null,
        TypeOfNumber.ALPHANUMERIC,
        NumberingPlanIndicator.UNKNOWN,
        "Uwiano",
        TypeOfNumber.INTERNATIONAL,
        NumberingPlanIndicator.ISDN,
        "254723624727",
        new ESMClass(),
        (byte) 0,
        (byte) 0,
        null,
        null,
        new RegisteredDelivery(SMSCDeliveryReceipt.DEFAULT),
        (byte) 0,
        new GeneralDataCoding(Alphabet.ALPHA_LATIN1, MessageClass.CLASS1, false),
        (byte) 0,
        message.getBytes("ISO-8859-1")
//        message.getBytes()
);
```

**Comment by pmoerenhout** [comment]
Most SMSC default alphabets are some sort of Latin 1 (ISO-8559-1). But it could also be GSM alphabet. Your string contains the â, ê, î, ô, û, é and ï characters which are not part of the GSM alphabet (https://en.wikipedia.org/wiki/GSM_03.38). The GSM alphabet you can find in the jcharset artifact (https://search.maven.org/#artifactdetails%7Cnet.freeutils%7Cjcharset%7C2.0%7Cjar). When using the default alphabet, you better can specify the Java charset to be using instead of message.getBytes(). You could try to code the pound symbol as 0x01 (the value in the GSM alphabet).

**Comment by kamochu** [comment]
@pmoerenhout thanks for the information and your insights. My GSM7bit charset class had characters missing and I have added them and all is okay now.

Thank you for help and be blessed!
