### ISSUE TITLE
Aboult messageId

### ISSUE THREAD

**Issue by wsrfzd** [opentelecoms-org/jsmpp#85]
Hi,
I don't want to use the message id generated by smsc. can i custom an message id passed to smsc via MT and get this custom message id through the delivery receipt. which parameter can i use?

**Comment by pmoerenhout** [comment]
For MT messages, submitted by an jSMPP ESME, to the SMSC, it's the SMSC which generates the message ID. In your application you can process the received String it in any way you like. The delivery receipt is also generated by the SMSC. You can define a custom delivery receipt class to handle the SMSC format, and then process it further.

If you implement not an ESME but an SMSC, you can extend the MessageIDGenerator interface. There is for example an RandomDecimalMessageIDGenerator class in the repo.

So the answer is that the messageid in the delivery receipt is in the SMSC context defined. The ESME does not have any control over the format received.

**Comment by wsrfzd** [comment]
Okay i see. Thank you. 
I also tried some OptionalParameters in these two days but did not achieve my purpose.

**Comment by pmoerenhout** [comment]
OK, if you need more clarification, let me know.
