### ISSUE TITLE
Help: Please guide me how to receive SMS over SMPP from SMSC

### ISSUE THREAD

**Issue by rahul-pharande** [opentelecoms-org/jsmpp#86]
I've referred to examples given here - https://github.com/opentelecoms-org/jsmpp/tree/master/jsmpp-examples/src/main/java/org/jsmpp/examples
However I didn't find example on how to receive SMS. Please point me to class/java file which I can refer to.

In general, I've requirement to Send and Receive SMS messages from SMS aggregator which works on SMPP. I'm exploring jSMPP for it.

**Comment by rahul-pharande** [comment]
@pmoerenhout Is it ReceiveSubmittedMessageExample.java or MessageReceiverListenerImpl.java (with else part line 62)?

**Comment by pmoerenhout** [comment]
The SimpleSubmitSimpleReceiveExample implements a simple SMPP client which (ESME) can receive the deliver_sm in the onAcceptDeliverSm() method, in the MessageReceiverListener.

The ReceiveSubmittedMessageExample implements an SMPP server (a SMSC). The message listener is here **Server**MessageReceiverListener, which implicates that it will act as server (SMSC).

**Comment by rahul-pharande** [comment]
Thanks for pointers. Could u pls let us know how can we implement receiving of MO messages from SMSC.

**Comment by pmoerenhout** [comment]
The SMSC will send the SMPP client the deliver_sm request. In the MessageReceiverListener the onAcceptDeliverSm will be called. In the SimpleSubmitRegisteredExample, you see in the MessageReceiverListenerImpl the onAcceptDeliverSm. Either the incoming deliver_sm PDU contains a delivery receipt or is a regular (MO) message. Their you have to implement your code for handling the message into your application. The jSMPP API will respond with the deliver_sm_resp PDU.

**Comment by rahul-pharande** [comment]
I've implemented in same way but not tested yet. However thanks for your inputs.
