### ISSUE TITLE
how to submit and receive a LongMessage

### ISSUE THREAD

**Issue by liangfutang** [opentelecoms-org/jsmpp#87]
Hi, your jsmpp project is very good when i see it ,and it helps me very much, but when i want to submit a long message,my cellphone will receice several messages. Can you tell me how to submit a long message, than my cellphone will receive just one long message

**Comment by pmoerenhout** [comment]
On the GSM network radio channel, the GSM SMS will always consist of 140 octets (bytes) maximum. Multiple SMS can be combined (concatenated) by the ME (the handset), and are then represented as one message to the user.
Other networks may have longer message sizes for the radio packet. Also SMSC's will split the SMS into multiple concatenated SMS as convenience.

If you receive it as multiple message, are you sure the User Data Headers (UDH) will contain the Information Elements (IE) with the concatenation elements ?

You could check by sending the SMS to a GSM modem (with AT commands) where you can check the complete message. Also if the SMSC does add the concatenation, you can do it explicitly in the message itself.

See: https://en.wikipedia.org/wiki/SMS#Message_size

**Comment by liangfutang** [comment]
Thanks for your reply, because i am developing a SMS platform for company, and i need to consider the larger content , so i test it like org.jsmpp.examples.SubmitLongMessageExample.java to submit it, but i have receive multiple message, Multiple SMS just have not be combined by ME

**Comment by pmoerenhout** [comment]
When you want to handle the long message send by your client, you can check if the SMSC can handle long messages. When your code handles the break down into SMS, you can use SMPP Optional parameters for the concatenating, or do it in the UDH directly. For mobiles, the combining is always implemented, either 8 or 16 bit reference numbering. Sometimes the mobile has a limit in the total number of SMS it can concatenate into 1 long message.
