### ISSUE TITLE
IOException after unbind

### ISSUE THREAD

**Issue by programervn** [opentelecoms-org/jsmpp#88]
I used jsmpp 2.3.6, and ran SimpleSubmitExample for test.
After session.unbindAndClose(); I got exeption.
The sample code is:
public static void main(String[] args) throws InterruptedException {
        SMPPSession session = new SMPPSession();
        try {
            LOGGER.info("Connecting");
            String systemId = session.connectAndBind("localhost", 8056, new BindParameter(BindType.BIND_TX, "test", "test", "cp", TypeOfNumber.UNKNOWN, NumberingPlanIndicator.UNKNOWN, null));
            LOGGER.info("Connected with SMSC with system id {}", systemId);

            try {
                String messageId = session.submitShortMessage("CMT",
                    TypeOfNumber.INTERNATIONAL, NumberingPlanIndicator.UNKNOWN, "1616",
                    TypeOfNumber.INTERNATIONAL, NumberingPlanIndicator.UNKNOWN, "628176504657",
                    new ESMClass(), (byte)0, (byte)1,  TIME_FORMATTER.format(new Date()), null,
                    new RegisteredDelivery(SMSCDeliveryReceipt.DEFAULT), (byte)0, new GeneralDataCoding(Alphabet.ALPHA_DEFAULT, MessageClass.CLASS1, false), (byte)0,
                    "jSMPP simplify SMPP on Java platform".getBytes());
                LOGGER.info("Message submitted, message_id is {}", messageId);
            } catch (PDUException e) {
                // Invalid PDU parameter
                LOGGER.error("Invalid PDU parameter", e);
            } catch (ResponseTimeoutException e) {
                // Response timeout
                LOGGER.error("Response timeout", e);
            } catch (InvalidResponseException e) {
                // Invalid response
                LOGGER.error("Receive invalid response", e);
            } catch (NegativeResponseException e) {
                // Receiving negative response (non-zero command_status)
                LOGGER.error("Receive negative response, e");
            } catch (IOException e) {
                LOGGER.error("IO error occured", e);
            }

            session.unbindAndClose();

        } catch (IOException e) {
            LOGGER.error("Failed connect and bind to host", e);
        }
    }

The exception logs is:
10/08/2018 - 16:56:38.598 [main] INFO : com.vivas.sms.SimpleSubmitExample.main(51) - Connecting
10/08/2018 - 16:56:38.635 [main] DEBUG: org.jsmpp.session.SMPPSession.connectAndBind(217) - Connect and bind to localhost port 8056
10/08/2018 - 16:56:38.705 [main] INFO : org.jsmpp.session.SMPPSession.connectAndBind(223) - Connected to localhost/127.0.0.1
10/08/2018 - 16:56:38.730 [main] DEBUG: org.jsmpp.DefaultPDUSender.writeAndFlush(450) - Sending SMPP message 00 00 00 21 00 00 00 02 00 00 00 00 00 00 00 01 74 65 73 74 00 74 65 73 74 00 63 70 00 34 00 00 00 
10/08/2018 - 16:56:38.737 [PDUReaderWorker: org.jsmpp.session.SMPPSession@6576fe71] INFO : org.jsmpp.session.SMPPSession$PDUReaderWorker.run(580) - Starting PDUReaderWorker
10/08/2018 - 16:56:38.754 [pool-1-thread-1] DEBUG: org.jsmpp.session.PDUProcessTask.run(54) - Received SMPP message PDUHeader(31, 80000002, 00000000, 1) 53 6d 73 63 20 53 69 6d 75 6c 61 74 6f 72 00 
10/08/2018 - 16:56:38.756 [pool-1-thread-1] DEBUG: org.jsmpp.session.state.SMPPSessionOpen.processBindResp(57) - Bind Response header (31, 80000002, 00000000, 1)
10/08/2018 - 16:56:38.759 [main] DEBUG: org.jsmpp.session.AbstractSession.executeSendCommand(292) - bind response with sequence 1 received for session 06d2dfaf
10/08/2018 - 16:56:38.791 [main] INFO : org.jsmpp.bean.OptionalParameters.get(250) - Optional Parameter Tag class org.jsmpp.bean.OptionalParameter$Sc_interface_version not found
10/08/2018 - 16:56:38.791 [main] INFO : org.jsmpp.session.SMPPSession$BoundSessionStateListener.onStateChange(662) - Changing processor degree to 3
10/08/2018 - 16:56:38.791 [main] INFO : com.vivas.sms.SimpleSubmitExample.main(53) - Connected with SMSC with system id Smsc Simulator
10/08/2018 - 16:56:38.791 [EnquireLinkSender: org.jsmpp.session.SMPPSession@6576fe71] DEBUG: org.jsmpp.session.AbstractSession$EnquireLinkSender.run(457) - Starting EnquireLinkSender for session 06d2dfaf
10/08/2018 - 16:56:38.811 [main] DEBUG: org.jsmpp.DefaultPDUSender.writeAndFlush(450) - Sending SMPP message 00 00 00 68 00 00 00 04 00 00 00 00 00 00 00 02 43 4d 54 00 01 00 31 36 31 36 00 01 00 36 32 38 31 37 36 35 30 34 36 35 37 00 00 00 01 31 38 30 38 31 30 31 36 35 36 33 38 37 32 38 2b 00 00 00 00 11 00 24 6a 53 4d 50 50 20 73 69 6d 70 6c 69 66 79 20 53 4d 50 50 20 6f 6e 20 4a 61 76 61 20 70 6c 61 74 66 6f 72 6d 
10/08/2018 - 16:56:38.821 [pool-1-thread-2] DEBUG: org.jsmpp.session.PDUProcessTask.run(54) - Received SMPP message PDUHeader(25, 80000004, 00000000, 2) 53 6d 73 63 32 30 30 36 00 
10/08/2018 - 16:56:38.821 [main] DEBUG: org.jsmpp.session.AbstractSession.executeSendCommand(292) - submit_sm response with sequence 2 received for session 06d2dfaf
10/08/2018 - 16:56:38.831 [main] INFO : com.vivas.sms.SimpleSubmitExample.main(62) - Message submitted, message_id is Smsc2006
10/08/2018 - 16:56:38.831 [main] DEBUG: org.jsmpp.session.AbstractSession.unbindAndClose(388) - Unbind and close sesssion 06d2dfaf
10/08/2018 - 16:56:38.831 [main] DEBUG: org.jsmpp.DefaultPDUSender.writeAndFlush(450) - Sending SMPP message 00 00 00 10 00 00 00 06 00 00 00 00 00 00 00 03 
10/08/2018 - 16:56:38.841 [pool-1-thread-3] DEBUG: org.jsmpp.session.PDUProcessTask.run(54) - Received SMPP message PDUHeader(16, 80000006, 00000000, 3) 
10/08/2018 - 16:56:38.841 [main] DEBUG: org.jsmpp.session.AbstractSession.executeSendCommand(292) - unbind response with sequence 3 received for session 06d2dfaf
10/08/2018 - 16:56:38.851 [main] DEBUG: org.jsmpp.session.AbstractSession.close(204) - Close session 06d2dfaf
10/08/2018 - 16:56:38.851 [main] DEBUG: org.jsmpp.session.AbstractSession.close(218) - Stop enquireLinkSender for session 06d2dfaf
10/08/2018 - 16:56:38.851 [EnquireLinkSender: org.jsmpp.session.SMPPSession@6576fe71] DEBUG: org.jsmpp.session.AbstractSession$EnquireLinkSender.run(486) - EnquireLinkSender stopped for session 06d2dfaf
10/08/2018 - 16:56:38.851 [main] DEBUG: org.jsmpp.session.AbstractSession.close(230) - Close session context 06d2dfaf in state BOUND_TX
10/08/2018 - 16:56:38.851 [PDUReaderWorker: org.jsmpp.session.SMPPSession@6576fe71] WARN : org.jsmpp.session.SMPPSession$PDUReaderWorker.readPDU(622) - IOException while reading:
java.net.SocketException: Socket Closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at org.jsmpp.DefaultPDUReader.readPDUHeader(DefaultPDUReader.java:40)
	at org.jsmpp.session.SMPPSession$PDUReaderWorker.readPDU(SMPPSession.java:598)
	at org.jsmpp.session.SMPPSession$PDUReaderWorker.run(SMPPSession.java:582)
10/08/2018 - 16:56:38.861 [PDUReaderWorker: org.jsmpp.session.SMPPSession@6576fe71] DEBUG: org.jsmpp.session.AbstractSession.close(204) - Close session 06d2dfaf
10/08/2018 - 16:56:38.861 [PDUReaderWorker: org.jsmpp.session.SMPPSession@6576fe71] DEBUG: org.jsmpp.session.AbstractSession.close(204) - Close session 06d2dfaf
10/08/2018 - 16:56:38.861 [PDUReaderWorker: org.jsmpp.session.SMPPSession@6576fe71] INFO : org.jsmpp.session.SMPPSession$PDUReaderWorker.run(593) - PDUReaderWorker stop

**Comment by pmoerenhout** [comment]
When you send the unbind, the remote partly send the unbind_response, maybe wait a little and then close the TCP connection. Before the client disconnect, the remote party already disconnected. I could maybe not throw an exception in this case, as it's a normal behaviour...

**Comment by PascalSchumacher** [comment]
@pmoerenhout If possible and safe it would be great if this exceptions was suppressed (or logged on a lower level than `warn`).

**Comment by pmoerenhout** [comment]
I have changed the logging for IOException handling in the readPDU calls. Could you see if this is sufficient?

**Comment by PascalSchumacher** [comment]
I build jsmpp for source and ran a few tests. The exception logged on warn level is gone. Thank you very much!

It would be great to have a jsmpp release containing this change.

**Comment by PascalSchumacher** [comment]
I guess this can be closed after the fix in https://github.com/opentelecoms-org/jsmpp/commit/2a3b4824290f0aa604f4c748286480a3b48403ef was released with jsmpp `2.3.7`?

**Comment by pmoerenhout** [comment]
Fixed with release 2.3.7.

**Comment by programervn** [comment]
> Fixed with release 2.3.7.

Thanks, problem was resolved
