### ISSUE TITLE
Long message PDU Invalid error

### ISSUE THREAD

**Issue by Sagaragrawal** [opentelecoms-org/jsmpp#90]
HI I have been trying to send longer messages with length more then 254. I tried UCS_16 and yet I receive the error. Is their a way to send longer messages without splitting them.

**Comment by pmoerenhout** [comment]
Hi, do you have some logging to share? Did you put the long message in the short_message or in the optional payload parameter?

**Comment by stone1883** [comment]
> Hi, do you have some logging to share? Did you put the long message in the short_message or in the optional payload parameter?

Hi pmoerenhout, I've met the same problem, and after that I've set the short message as null, and add the optional parameter message_payload into the method of submitShortMessage:
new OptionalParameter[] { new OptionalParameter.Message_payload(content) };

But, when I do submitSM, it throw NullpointException.

**Comment by pmoerenhout** [comment]
I committed the fix in DefaultPDUSender which replace the null valued shortMessage with new byte[]{}.
