### ISSUE TITLE
SMPPSession is getting disconnected very frequently

### ISSUE THREAD

**Issue by hiriadka** [opentelecoms-org/jsmpp#91]
Hi,
Please give us some suggestions on below error, unable to debug what is the issue.
In one of our production environments we are facing below error
**org.jsmpp.session.state.AbstractGenericSMPPSessionBound - No request found for PDUHeader(16, 80000015, 00000000, 121735)**
This is just an error logger in JSMPP library and no exception is thrown.

When this issue occurs?

After this issue occurs current SMPPSession is getting disconnected.
We are not facing this error with simulators it occurs only in production environment.

**Comment by pmoerenhout** [comment]
This error is logged, when an enquire_link response (80000015) is received, but the corresponding request cannot be found. The sequence number 121735 could not be found. A detailed trace should reveal if the sequence was sent by the session. How is the setup? Do you use a single session, or do you have multiple sessions ?

**Comment by hiriadka** [comment]
> This error is logged, when an enquire_link response (80000015) is received, but the corresponding request cannot be found. The sequence number 121735 could not be found. A detailed trace should reveal if the sequence was sent by the session. How is the setup? Do you use a single session, or do you have multiple sessions ? Is the session dropped by the remote party or your jSMPP client ?

We have multiple SMPP sessions, by the dumps we are not able to rectify which side is the issue.
According to TCP dumps enquirelink response is received but in our logs we have seen above error.
Due to which session is getting disconnected. Below is the snapshot of enquire link request and response

![image](https://user-images.githubusercontent.com/42958172/45409765-b8b03600-b68d-11e8-9971-dfe4fab5e54b.png)


![image](https://user-images.githubusercontent.com/42958172/45409666-74bd3100-b68d-11e8-987d-9f8f7dc99f38.png)

![image](https://user-images.githubusercontent.com/42958172/45409703-8bfc1e80-b68d-11e8-8577-f386aedc2f48.png)

If there is delay in network will this issue pop up?

**Comment by pmoerenhout** [comment]
The delay is minimal (2ms) according to the TCP dump. The standard transaction timer is 2000ms. Did you use another value? Does the logging indicates other problems? Is the problem under heavy traffic or also when the session is idle ?
