### ISSUE TITLE
deliver_sm

### ISSUE THREAD

**Issue by prancius** [opentelecoms-org/jsmpp#94]
How to send deliver_sm to SMC. 

  session.setMessageReceiverListener(new MessageReceiverListener() {

do not send deliver_sm, how to send this command manually?
I need to read messages in ESME which comes from mobile to SMC
Thanks

**Comment by pmoerenhout** [comment]
The deliver_sm is only send from the SMSC towards the ESME. If you want to code an SMSC server, to send deliver_sm, jSMPP also supports that. But an ESME cannot send deliver_sm to the SMSC. Or are you implementing an routing entity?
