### ISSUE TITLE
How to support Spanish?

### ISSUE THREAD

**Issue by wenmingma** [opentelecoms-org/jsmpp#96]
My project run base on the Redhat Linux.
When I send sms inculudes special Spanish word like ñ,á and so on, but the jsmpp can not display correctly.
How can the jsmpp support Spanish?
Thanks in advance!

**Comment by wenmingma** [comment]
the special spanish words are like this
á é í ó ú ü ñ Á É Í Ó Ú Ü Ñ

**Comment by wenmingma** [comment]
### ### ### ### ddd****
### ddss
**ds**
_dsds_
#25 32323
##22
###333
####444

**Comment by pmoerenhout** [comment]
Hi, did you use the Spanish shift table as described in https://en.wikipedia.org/wiki/GSM_03.38. By setting the user data header, the end device should display this extended table characters like the á. Others like é and ñ are defined in the standard GSM 7-bit table. You could also use UCS-2 encoding, but that will half the capacity.

**Comment by wenmingma** [comment]
Thanks dear sir,
In my bash_profile, I add the following content，bug it not works.
export LANG="UCS-2"
Can you help to use the UCS-2 encoding?
Thanks

**Comment by pmoerenhout** [comment]
I see you want to display the special characters in your terminal when you set LANG variable. So:
When your terminal is set to UTF-8, and your byte stream is encoded in GSM 7 bit or some other encoding, your terminal will interpret as UTF-8, which can display garbled characters. You'll have to convert to the terminal characters set (UTF-8 in most cases) when you put these strings into your log.

Or do you have problems on your mobile device getting the special characters?
