### ISSUE TITLE
How to set the UDH in SubmitLongMessageExample.java

### ISSUE THREAD

**Issue by wenmingma** [opentelecoms-org/jsmpp#97]
Dear Sir,
Can you tell me how to set the UDH in SubmitLongMessageExample.java file?
I want to send a long message and I tried to append the UDH number before the message, but it not worked.
Thanks very much!

**Comment by pmoerenhout** [comment]
The UDH is part of the UD message. When The UDHI is set (in the ESMClass), the first byte in the message is the length of the UDH part. The mobile will, when the UDHI is set, interpret the UDH bytes from the message.
See: https://en.wikipedia.org/wiki/User_Data_Header

**Comment by wenmingma** [comment]
Thanks very much.
We solved the problem with your help.
